// Mock data: Map markers for GIS
export type MarkerSeverity = "low" | "moderate" | "high" | "critical";

export interface MapMarker {
  id: string;
  lat: number;
  lng: number;
  diseaseName: string;
  diseaseType: "disease" | "pest";
  cropName: string;
  severity: MarkerSeverity;
  riskLevel: "low" | "medium" | "high" | "critical";
  district: string;
  village: string;
  reportsCount: number;
  verifiedCount: number;
  lastReported: string;
  verified: boolean;
}

// Maharashtra-centric coordinates
export const MAP_MARKERS: MapMarker[] = [
  {
    id: "m-001",
    lat: 20.7439,
    lng: 78.6255,
    diseaseName: "Pink Bollworm",
    diseaseType: "pest",
    cropName: "Cotton",
    severity: "critical",
    riskLevel: "critical",
    district: "Wardha",
    village: "Arvi",
    reportsCount: 14,
    verifiedCount: 11,
    lastReported: "2026-09-09T10:23:00Z",
    verified: true,
  },
  {
    id: "m-002",
    lat: 18.4088,
    lng: 76.5604,
    diseaseName: "Yellow Mosaic Virus",
    diseaseType: "disease",
    cropName: "Soybean",
    severity: "high",
    riskLevel: "high",
    district: "Latur",
    village: "Udgir",
    reportsCount: 9,
    verifiedCount: 6,
    lastReported: "2026-09-08T14:45:00Z",
    verified: true,
  },
  {
    id: "m-003",
    lat: 19.9975,
    lng: 73.7898,
    diseaseName: "Aphid Infestation",
    diseaseType: "pest",
    cropName: "Wheat",
    severity: "moderate",
    riskLevel: "medium",
    district: "Nashik",
    village: "Dindori",
    reportsCount: 5,
    verifiedCount: 2,
    lastReported: "2026-09-07T09:10:00Z",
    verified: false,
  },
  {
    id: "m-004",
    lat: 16.7045,
    lng: 74.2383,
    diseaseName: "Downy Mildew",
    diseaseType: "disease",
    cropName: "Grape",
    severity: "high",
    riskLevel: "high",
    district: "Sangli",
    village: "Tasgaon",
    reportsCount: 7,
    verifiedCount: 5,
    lastReported: "2026-09-06T16:20:00Z",
    verified: true,
  },
  {
    id: "m-005",
    lat: 19.8762,
    lng: 75.3433,
    diseaseName: "Late Blight",
    diseaseType: "disease",
    cropName: "Tomato",
    severity: "moderate",
    riskLevel: "medium",
    district: "Aurangabad",
    village: "Phulambri",
    reportsCount: 3,
    verifiedCount: 1,
    lastReported: "2026-09-05T11:30:00Z",
    verified: false,
  },
  {
    id: "m-006",
    lat: 21.1458,
    lng: 79.0882,
    diseaseName: "Leaf Spot",
    diseaseType: "disease",
    cropName: "Soybean",
    severity: "low",
    riskLevel: "low",
    district: "Nagpur",
    village: "Kalmeshwar",
    reportsCount: 2,
    verifiedCount: 0,
    lastReported: "2026-09-04T08:00:00Z",
    verified: false,
  },
  {
    id: "m-007",
    lat: 17.6599,
    lng: 75.9064,
    diseaseName: "Powdery Mildew",
    diseaseType: "disease",
    cropName: "Grape",
    severity: "low",
    riskLevel: "low",
    district: "Solapur",
    village: "Mohol",
    reportsCount: 4,
    verifiedCount: 3,
    lastReported: "2026-09-03T13:15:00Z",
    verified: true,
  },
  {
    id: "m-008",
    lat: 20.6188,
    lng: 77.7533,
    diseaseName: "Stem Borer",
    diseaseType: "pest",
    cropName: "Sugarcane",
    severity: "critical",
    riskLevel: "critical",
    district: "Akola",
    village: "Barshitakli",
    reportsCount: 12,
    verifiedCount: 10,
    lastReported: "2026-09-09T06:45:00Z",
    verified: true,
  },
  {
    id: "m-009",
    lat: 21.0077,
    lng: 76.7767,
    diseaseName: "Root Rot",
    diseaseType: "disease",
    cropName: "Cotton",
    severity: "high",
    riskLevel: "high",
    district: "Buldhana",
    village: "Chikhli",
    reportsCount: 6,
    verifiedCount: 4,
    lastReported: "2026-09-08T09:30:00Z",
    verified: true,
  },
  {
    id: "m-010",
    lat: 18.0024,
    lng: 74.0032,
    diseaseName: "Thrips",
    diseaseType: "pest",
    cropName: "Onion",
    severity: "moderate",
    riskLevel: "medium",
    district: "Pune",
    village: "Baramati",
    reportsCount: 8,
    verifiedCount: 5,
    lastReported: "2026-09-07T14:00:00Z",
    verified: true,
  },
];
